//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNEY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOURNEY()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public decimal JOURNEY_ID { get; set; }
        public Nullable<decimal> TRAIN_ID { get; set; }
        public Nullable<decimal> DEPARTURE_STATION_ID { get; set; }
        public Nullable<decimal> DESTINATION_STATION_ID { get; set; }
        public Nullable<System.DateTime> DURATION { get; set; }
        public Nullable<System.DateTime> JOURNEY_DATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> PLATFORM_DEPARTURE { get; set; }
        public Nullable<System.DateTime> DEPARTURE_TIME { get; set; }
        public Nullable<System.DateTime> ARRIVAL_TIME { get; set; }
        public Nullable<decimal> PLATFORM_ARRIVAL { get; set; }
    
        public virtual TRAIN TRAIN { get; set; }
        public virtual PLATFORM PLATFORM { get; set; }
        public virtual STATION STATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
