//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATFORM
    {
        public decimal PLATFORM_ID { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual JOURNEY JOURNEY { get; set; }
    }
}
